name: Build

on:
  - push
  - pull_request

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - windows-latest
          - windows-11-arm
          - macos-15-intel
          - macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
      - run: python -m pip install cibuildwheel==3.2.0
      - run: python -m cibuildwheel
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: ./wheelhouse/*.whl
